#----------------------------#
# KnockbackFFA by humandavey #
#----------------------------#

config:
  default-spawn:
    world: "world"
    x: 0
    y: 80
    z: 0
    yaw: 0
    pitch: 0
  map-rotation-minutes: 10

data:
  "testmap":
    spawn:
      world: "world"
      x: 0
      y: 64
      z: 0
      yaw: 0
      pitch: 0
    corner-1:
      world: "world"
      x: 0
      y: 64
      z: 0
    corner-2:
      world: "world"
      x: 0
      y: 64
      z: 0

inventories:
  "18277c8ab2e2446380a76ee5ba004a94": "stick:0;bow:1;blocks:4;arrows:8"