#----------------------------#
# KnockbackFFA by humandavey #
#----------------------------#

data:
  map-world: "world"
  "testmap":
    spawn:
      x: 0
      y: 64
      z: 0
      yaw: 0
      pitch: 0
    corner-1:
      x: 0
      y: 64
      z: 0
    corner-2:
      x: 0
      y: 64
      z: 0